### ISSUE TITLE
Adicionar Branch 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/behaviors#1]
![2021-08-16_11-55](https://user-images.githubusercontent.com/86842154/129584187-c2735d85-c061-4364-b7a8-2cd04ca4cc61.png)

![2021-08-16_11-55_1](https://user-images.githubusercontent.com/86842154/129584209-944a8398-3371-4a53-abdb-1dec3a78ef09.png)

**Comment by verdanatech-luana** [comment]
Branch 9.5-dev criada.

![2021-08-16_13-38](https://user-images.githubusercontent.com/86842154/129598826-a5e92290-fb70-4bfa-be36-b3c25969da7b.png)

![2021-08-16_13-39](https://user-images.githubusercontent.com/86842154/129598847-b7a24e52-c00f-4622-9b77-60d70b8e389c.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando no GLPI - 9.5
![TesteBV](https://user-images.githubusercontent.com/80538863/129726290-f34e8baa-5caa-4856-bcb4-d205873753d2.png)
